Enter file contents herename: Swift CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Swift
      uses: SwiftActions/setup-swift@v2
      with:
        swift-version: '5.5'

    - name: Install dependencies
      run: |
        swift package resolve

    - name: Build
      run: |
        swift build

    - name: Test
      run: |
        swift test
